AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Parameters for the new account to be created
        Parameters:
          - MasterLambdaArn
          - AccountEmail
          - OrganizationalUnitName
          - AccountName
          - StackName
          - StackRegion
          - SourceBucket
          - CloudTrailCWLogsRetentionTime
          - CloudTrailLogS3DataEvents
          - CloudTrailEncryptS3Logs
          - ConfigSnapshotFrequency
          - GuardDutyEmailAddress
          - BaselineTemplate

Parameters:
  MasterLambdaArn:
    Description: "Enter the ARN for the lambda function in your root account for creating accounts (OUTPUTS from Infrastructure Setup CloudFormation)"
    Type: String

  AccountEmail:
   Description: "Email address of the AWS account to be created"
   Type: String
   AllowedPattern: ".+"
   ConstraintDescription: "Must provide a valid email address"

  AccountName:
    Description: "Name of the new AWS Account Name"
    Type: String
    AllowedPattern: ".+"
    ConstraintDescription: "Provide the account name"

  OrganizationalUnitName:
    Description: "Name of the organizational unit (OU) to which the account should be moved to."
    Type: String
    Default: "None"
    AllowedPattern: ".+"

  StackRegion:
    Description: "Region for deploying the baseline template in the vended account"
    Default: "us-west-2"
    Type: String
    AllowedPattern: ".+"
    AllowedValues: ["us-east-2","us-east-1","us-west-1","us-west-2","ap-northeast-1","ap-northeast-2","ap-northeast-3","ap-south-1","ap-southeast-1","ap-southeast-2","ca-central-1","cn-north-1","cn-northwest-1","eu-central-1","eu-west-1","eu-west-2","eu-west-3","sa-east-1"]
    ConstraintDescription: "Must be a valid AWS region"

  SourceBucket:
    Description: "Name of the S3 bucket holding the baseline template file"
    Type: String
    
  BaselineTemplate:
    Description: "Baseline template to be deployed in the vended account."
    Type: String
    Default: "Baseline.yml" 
    
  CloudTrailCWLogsRetentionTime:
    Type: Number
    Description: 'Number of days to retain logs in CloudWatch Logs. 0=Forever. Default 1 year, note logs are stored in S3 default 10 years'
    Default: '90'
  CloudTrailLogS3DataEvents:
    Type: String
    Description: 'OPTIONAL: These events provide insight into the resource operations performed on or within S3'
    Default: 'Yes'
    AllowedValues:
      - 'No'
      - 'Yes'
  CloudTrailEncryptS3Logs:
    Type: String
    Description: 'OPTIONAL: Use KMS to enrypt logs stored in S3. A new key will be created'
    Default: 'Yes'
    AllowedValues:
      - 'No'
      - 'Yes'
  #Config
  ConfigSnapshotFrequency:
    Type: String
    Description: AWS Config configuration snapshot frequency
    Default: Six_Hours
    AllowedValues:
      - One_Hour
      - Three_Hours
      - Six_Hours
      - Twelve_Hours
      - TwentyFour_Hours

  #GuardDuty
  GuardDutyEmailAddress:
    Type: String
    Default: 'someone@example.com'
    Description: Enter the email address that will receive the alerts


Resources:

  TriggerAccountLambda:
    Type: "Custom::TriggerAccountLambda"
    DeletionPolicy: Retain
    Properties:
      ServiceToken: !Ref MasterLambdaArn
      AccountEmail : !Ref AccountEmail
      AccountName : !Ref AccountName
      OrganizationalUnitName: !Ref 'OrganizationalUnitName'
      StackName : 'avm-baseline-stack'
      StackRegion : !Ref StackRegion
      ServiceCatalogUserName : 'service-catalog-user'
      ServiceCatalogUserPassword : 'Password@123'
      SourceBucket : !Ref SourceBucket
      BaselineTemplate: !Ref BaselineTemplate
      CloudTrailCWLogsRetentionTime: !Ref CloudTrailCWLogsRetentionTime
      CloudTrailLogS3DataEvents: !Ref CloudTrailLogS3DataEvents
      ConfigSnapshotFrequency: !Ref ConfigSnapshotFrequency
      GuardDutyEmailAddress: !Ref GuardDutyEmailAddress
      CloudTrailEncryptS3Logs: !Ref CloudTrailEncryptS3Logs
      
      
      

Outputs:
  Message:
    Description: Execution Status
    Value: !GetAtt 'TriggerAccountLambda.Message'

  AccountID:
    Description: AWS Account ID of the newly vended account
    Value: !GetAtt 'TriggerAccountLambda.AccountID'

  Username:
    Description: Username of IAM user created in the newly vended account
    Value: !GetAtt 'TriggerAccountLambda.Username'

  LoginURL:
    Description: Login URL for the newly vended account
    Value: !GetAtt 'TriggerAccountLambda.LoginURL'
